sanity check ATMOSFOAM_SRC directory

diff --git a/Allwmake b/Allwmake
--- a/Allwmake
+++ b/Allwmake
@@ -7,5 +7,11 @@ cd ${0%/*} || exit 1    # run from this directory
     exit 1
 }
 
+[ -d "$ATMOSFOAM_SRC" ] || {
+    echo "Error: ATMOSFOAM_SRC directory does not exist"
+    echo "    Check the OpenFOAM entries in your dot-files and source them."
+    exit 1
+}
+
 src/Allwmake $*
 applications/Allwmake $*
